# Drawing Conclusions Using Groupby

In [12]:
# Load `winequality_edited.csv`
import pandas as pd
import numpy as np

df = pd.read_csv('winequality_edited.csv')
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color,acidity_levels
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,Low
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red,Mod_High
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red,Medium
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red,Mod_High
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,Low

### Is a certain type of wine associated with higher quality? if so, which type is better in quality ?  white ــــــــــــــــــــ

In [13]:
# Find the mean quality of each wine type (red and white) with groupby

df.groupby(['color'], as_index=False)['quality'].mean()

   color   quality
0    red  5.636023
1  white  5.877909

### What level of acidity receives the highest average rating? low ــــــــــــــــــــــــــــــ

In [14]:
# create a column in the dataframe [acidity_levels] that tells you the levels of the acidity ['high', 'mod_high', 'medium', 'low'] according
# to the level of pH percentiles [min, 25% , 50%, 75%, max] 
# below 25% is high ---  25% to 50% is mod_high [moderately]  --- 50% to 75% medium ---- higher than 75% is low
# There are easier ways to do this than what you think [there is a specific pandas function for this]

In [15]:
df.pH.describe()
percent = [2.72, 3.11, 3.21, 3.32, 4.01]
levels = [ 'High', 'Mod_High', 'Medium', 'Low']
df['acidity_levels'] = pd.cut(df['pH'],  percent, labels = levels)
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color,acidity_levels
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,Low
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red,Mod_High
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red,Medium
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red,Mod_High
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,Low

In [16]:
# Groupby the newely created acidity level column and get the mean of the quality so you can decide which acidity level
# results in the best quality and answer the question  (low)

# df.groupby('quality').mean()
best = df.groupby(['acidity_levels'], as_index=False)['quality'].mean()
best

  acidity_levels   quality
0           High  5.783343
1       Mod_High  5.784540
2         Medium  5.850832
3            Low  5.859593

In [17]:
# Save changes for the next section as "winequality_edited.csv" -- do not make a stupid mistake !
df.to_csv('winequality_edited1.csv', index = False)